/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Traveler's Hub Design System — DESIGN.md
        // 값들이 CSS 변수(rgb(var(--color-x) / <alpha-value>))를 참조해서,
        // <html>에 'dark' 클래스만 붙으면(styles/index.css의 .dark 블록) 앱 전체가 자동으로 다크 테마로 바뀜.
        // 실제 라이트/다크 색상 값은 src/styles/index.css의 :root / .dark 참고.
        'primary':                  'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary':               'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container':        'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container':     'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'inverse-primary':          'rgb(var(--color-inverse-primary) / <alpha-value>)',
        'primary-fixed':            'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim':        'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed':         'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)',

        'secondary':                'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary':             'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-container':      'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container':   'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        'secondary-fixed':          'rgb(var(--color-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim':      'rgb(var(--color-secondary-fixed-dim) / <alpha-value>)',
        'on-secondary-fixed':       'rgb(var(--color-on-secondary-fixed) / <alpha-value>)',
        'on-secondary-fixed-variant':'rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)',

        'tertiary':                 'rgb(var(--color-tertiary) / <alpha-value>)',
        'on-tertiary':              'rgb(var(--color-on-tertiary) / <alpha-value>)',
        'tertiary-container':       'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-tertiary-container':    'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
        'tertiary-fixed':           'rgb(var(--color-tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim':       'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary-fixed':        'rgb(var(--color-on-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-fixed-variant':'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)',

        'error':                    'rgb(var(--color-error) / <alpha-value>)',
        'on-error':                 'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container':          'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container':       'rgb(var(--color-on-error-container) / <alpha-value>)',

        'surface':                  'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim':              'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright':           'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low':    'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container':        'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high':   'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest':'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'surface-variant':          'rgb(var(--color-surface-variant) / <alpha-value>)',
        'surface-tint':             'rgb(var(--color-surface-tint) / <alpha-value>)',
        'on-surface':               'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant':       'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'inverse-surface':          'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':       'rgb(var(--color-inverse-on-surface) / <alpha-value>)',

        'outline':                  'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant':          'rgb(var(--color-outline-variant) / <alpha-value>)',
        'background':               'rgb(var(--color-background) / <alpha-value>)',
        'on-background':            'rgb(var(--color-on-background) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':     ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm':    ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
      borderRadius: {
        'sm':      '0.25rem',
        DEFAULT:   '0.5rem',
        'md':      '0.75rem',
        'lg':      '1rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      spacing: {
        'unit':             '8px',
        'stack-sm':         '8px',
        'stack-md':         '16px',
        'stack-lg':         '32px',
        'stack-xl':         '64px',
        'gutter':           '24px',
        'margin-mobile':    '16px',
        'margin-desktop':   '64px',
        'container-max':    '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        'glow':       '0px 10px 30px rgba(33, 37, 41, 0.05)',
        'glow-hover': '0px 20px 40px rgba(33, 37, 41, 0.08)',
      },
    },
  },
  plugins: [],
}
