/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Traveler's Hub Design System — DESIGN.md
        'primary':                  '#24657e',
        'on-primary':               '#ffffff',
        'primary-container':        '#8ecae6',
        'on-primary-container':     '#0a566e',
        'inverse-primary':          '#93cfeb',
        'primary-fixed':            '#bde9ff',
        'primary-fixed-dim':        '#93cfeb',
        'on-primary-fixed':         '#001f2a',
        'on-primary-fixed-variant': '#004d64',

        'secondary':                '#635d57',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#eae1d9',
        'on-secondary-container':   '#69635d',
        'secondary-fixed':          '#eae1d9',
        'secondary-fixed-dim':      '#cdc5be',
        'on-secondary-fixed':       '#1f1b16',
        'on-secondary-fixed-variant':'#4b4640',

        'tertiary':                 '#934b00',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#ffb074',
        'on-tertiary-container':    '#7c3f00',
        'tertiary-fixed':           '#ffdcc4',
        'tertiary-fixed-dim':       '#ffb781',
        'on-tertiary-fixed':        '#301400',
        'on-tertiary-fixed-variant':'#703800',

        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',

        'surface':                  '#f7f9ff',
        'surface-dim':              '#d7dadf',
        'surface-bright':           '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f1f4f9',
        'surface-container':        '#ebeef3',
        'surface-container-high':   '#e5e8ee',
        'surface-container-highest':'#e0e3e8',
        'surface-variant':          '#e0e3e8',
        'surface-tint':             '#24657e',
        'on-surface':               '#181c20',
        'on-surface-variant':       '#40484c',
        'inverse-surface':          '#2d3135',
        'inverse-on-surface':       '#eef1f6',

        'outline':                  '#70787d',
        'outline-variant':          '#c0c8cd',
        'background':               '#f7f9ff',
        'on-background':            '#181c20',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':     ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm':    ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
      borderRadius: {
        'sm':      '0.25rem',
        DEFAULT:   '0.5rem',
        'md':      '0.75rem',
        'lg':      '1rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      spacing: {
        'unit':             '8px',
        'stack-sm':         '8px',
        'stack-md':         '16px',
        'stack-lg':         '32px',
        'stack-xl':         '64px',
        'gutter':           '24px',
        'margin-mobile':    '16px',
        'margin-desktop':   '64px',
        'container-max':    '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        'glow':       '0px 10px 30px rgba(33, 37, 41, 0.05)',
        'glow-hover': '0px 20px 40px rgba(33, 37, 41, 0.08)',
      },
    },
  },
  plugins: [],
}
